# Generated by Django 3.1.4 on 2021-01-15 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 11, 9, 23, 610284, tzinfo=utc)),
        ),
    ]
