# Generated by Django 3.1.4 on 2021-01-15 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210115_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 17, 8, 29, 355363)),
        ),
    ]
